version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: class_registration_app
      MYSQL_USER: localhost
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
  app:
    build: .
    container_name: class-registration-app-backend
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/class_registration_app
