name: deploy ecr

on:
  push:
    branches:
      - test

jobs:
  deploy-ecr:
    name: deploy ECR and App Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3.0.0

      # Node.jsのインストール
      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: echo
        run: echo "Helloworld"

      - name: Set up Docker
        uses: docker/setup-docker-action@v2
        with:
          version: latest

      - name: check for docker command is available
        run: docker --version
