name: deploy ecr

on:
  push:
    branches:
      - test

jobs:
  deploy-ecr:
    name: deploy frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3.0.0

      # Node.jsのインストール
      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: echo
        run: echo "Helloworld"
