name: deploy ecr

on:
  push:
    branches:
      - test

jobs:
  deploy-ecr:
    name: deploy ECR and App Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v3.0.0

      # Node.jsのインストール
      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: echo
        run: echo "Helloworld"

      - name: check for docker command is available
        run: docker --version

      # awsのクレデンシャルを解決
      - name: configure aws credencials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: deploy ecr
        run: aws cloudformation deploy --template-file cloudformation/template-backend-prepare.yaml --stack-name ecr

      - name: build app
        run: docker build . -t nest-app

      - name: login to ecr
        run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com

      - name: Push to ECR
        run: docker tag nest-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/nest-app:latest

      - name: push
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/nest-app:latest
