name: deploy ECR Repository

on:
  push:
    branches:
      - main
      - '*'

jobs:
  deploy-ECR-Repo:
    name: deploy ecr repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: configure aws credencials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Set up Docker
        uses: docker/setup-docker-action@v2
        with:
          version: latest

      - name: echo
        run: echo $(docker --version)
